#Logistics

In [ ]:
from google.colab import auth
auth.authenticate_user()

print('Authenticated')

Authenticated

In [ ]:
project_id = 'bigquerycourse-464720'

In [ ]:
%load_ext google.colab.data_table

#Deliveries in within 48 hours?

>This query counts the number of orders completed or returned in the second quarter of 2025 that were delivered within 48 hours. It groups the results by year and quarter, using the `orders` table from the look_ecommerce dataset.

In [ ]:
%%bigquery --project {project_id}
select
year_quarter as year_quarter,
count(order_id) as count_order_id,
from
(
select
format_datetime("%Y-%QQ",created_at)as year_quarter,
order_id as order_id,
created_at as created_at,
delivered_at as delivered_at,
TIMESTAMP_DIFF(delivered_at,created_at, HOUR) AS delivery_time
from
`bigquery-public-data.thelook_ecommerce.orders`
where
  status in ('Complete','Returned') and
  EXTRACT(QUARTER FROM created_at) = 2 and
  extract(YEAR FROM created_at) = 2025 and
  TIMESTAMP_DIFF(delivered_at,created_at, HOUR) <= 48
order by
  created_at asc
)
group by year_quarter
order by year_quarter